### ISSUE TITLE
核心特性如何实现，关键技术细节探讨

### ISSUE THREAD

**Issue by unclexiao** [dart-native/codegen#32]
> 自研超级通道，性能甩开官方 Channel 好几倍；
>  Native API 也被赋予了热重载功能

这两个想法非常超级棒！大前端开发者们表示无比兴奋！不过能请问下作者打算怎么做呢，有哪些关键思路？

目前我已独立开发并上线了一个100% Dart实现的项目：[Tell](https://app.tellers.cn/)，拿到融资并顺利扩充了团队，接下来希望继续在混编路上深耕。

期待作者能讲个大致方向，我们愿意加入本项目团队，积极参与社区建设。

**Comment by yulingtianxia** [comment]
@unclexiao  你好，这个库是自动生成代码的实现，bridge 的实现是在 https://github.com/dart-native/dart_native 里。可以参考下 readme 里提到的文章，里面有一些技术的介绍，比如这篇 http://yulingtianxia.com/blog/2019/11/28/DartObjC-Design/

目前还在开发中，iOS 侧实现度还算高一些，欢迎踩坑试用。同时也欢迎提 PR 共建。

**Comment by unclexiao** [comment]
好的，速读了文章，有点帮助的。持续关注中，希望之后能尽绵薄之力
